### ISSUE TITLE
Procedimientos casi correctos, resultados incorrectos

### ISSUE THREAD

**Issue by jevillanueva** [AASG2003/psg-ejercicio#2]
https://github.com/AASG2003/psg-ejercicio/blob/76e2eadb882cc368858f2e622677faddc0151828/tarea_sesion_05/ejercicio3.py#L6-L14

Revisar el resultado

288325 segundos son: 3 días, 8 horas, 5 minutos y 25 segundos

**Comment by AASG2003** [comment]
Corregido, lo hice mecánicamente y para convertir a días lo dividí entre 60 y no entre 24 xD
